# Generated by Django 5.2.4 on 2025-08-07 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asiento',
            name='clase',
            field=models.CharField(choices=[('Turista', 'Turista'), ('Ejecutiva', 'Ejecutiva')], default='Turista', max_length=20),
        ),
        migrations.AddField(
            model_name='asiento',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='asiento',
            name='ubicacion',
            field=models.CharField(choices=[('Ventana', 'Ventana'), ('Pasillo', 'Pasillo')], default='Pasillo', max_length=10),
        ),
        migrations.AddField(
            model_name='asiento',
            name='vuelo',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='gestion.vuelo'),
            preserve_default=False,
        ),
    ]
