# Generated by Django 5.2.4 on 2025-08-07 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_asiento_clase_asiento_disponible_asiento_ubicacion_and_more'),
    ]

    operations = [
    ]
