# Generated by Django 5.2.4 on 2025-08-07 22:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('gestion', '0003_add_clase_asiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asiento',
            name='disponible',
        ),
        migrations.RemoveField(
            model_name='asiento',
            name='ubicacion',
        ),
        migrations.RemoveField(
            model_name='boleto',
            name='asiento_alternativo',
        ),
        migrations.AlterField(
            model_name='asiento',
            name='fila',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='asiento',
            name='vuelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asientos', to='gestion.vuelo'),
        ),
        migrations.AlterField(
            model_name='avion',
            name='capacidad',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='avion',
            name='columnas',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='avion',
            name='filas',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='avion',
            name='matricula',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='pasajero',
            name='documento',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='gestion_usuarios', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='gestion_usuarios_permissions', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
