# Generated by Django 5.2.4 on 2025-08-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_fix_is_superuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pasajero',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_staff',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='destino',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='origen',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
