# Generated by Django 5.2.4 on 2025-08-13 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_usuario_is_staff_alter_usuario_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vuelo',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='vuelo',
            name='gestion_vue_origen_25a1c9_idx',
        ),
        migrations.RemoveIndex(
            model_name='vuelo',
            name='gestion_vue_fecha_s_3f8d62_idx',
        ),
    ]
